pub mod npm;
pub mod pnpm;
pub mod yarn;

use std::path::Path;

use crate::DependencyGraph;

/// Auto-detect and parse the lockfile in the given project directory.
/// Checks for pnpm-lock.yaml, package-lock.json, yarn.lock in that order.
pub fn detect_and_parse(project_dir: &Path) -> Result<DependencyGraph, String> {
    let candidates = [
        ("pnpm-lock.yaml", "pnpm" as &str),
        ("package-lock.json", "npm"),
        ("yarn.lock", "yarn"),
    ];

    for (filename, kind) in &candidates {
        let path = project_dir.join(filename);
        if path.exists() {
            let content = std::fs::read_to_string(&path)
                .map_err(|e| format!("Failed to read {filename}: {e}"))?;
            return match *kind {
                "pnpm" => pnpm::parse(&content),
                "npm" => npm::parse(&content),
                "yarn" => yarn::parse(&content),
                _ => unreachable!(),
            };
        }
    }

    Err("No lockfile found (looked for pnpm-lock.yaml, package-lock.json, yarn.lock)".to_string())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::LockfileType;
    use std::fs;

    #[test]
    fn test_detect_pnpm() {
        let dir = std::env::temp_dir().join("lockpick_test_detect_pnpm");
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();

        let content = r#"lockfileVersion: '9.0'
importers:
  .:
    dependencies:
      react:
        specifier: ^18.2.0
        version: 18.2.0
packages:
  react@18.2.0:
    resolution:
      integrity: sha512-fake
"#;
        fs::write(dir.join("pnpm-lock.yaml"), content).unwrap();

        let graph = detect_and_parse(&dir).unwrap();
        assert_eq!(graph.lockfile_type, LockfileType::Pnpm);

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_detect_npm() {
        let dir = std::env::temp_dir().join("lockpick_test_detect_npm");
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();

        let content = r#"{
  "name": "test",
  "version": "1.0.0",
  "lockfileVersion": 3,
  "packages": {
    "": { "name": "test", "version": "1.0.0", "dependencies": { "react": "^18.2.0" } },
    "node_modules/react": { "version": "18.2.0", "resolved": "https://registry.npmjs.org/react/-/react-18.2.0.tgz", "integrity": "sha512-fake" }
  }
}"#;
        fs::write(dir.join("package-lock.json"), content).unwrap();

        let graph = detect_and_parse(&dir).unwrap();
        assert_eq!(graph.lockfile_type, LockfileType::Npm);

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_detect_yarn() {
        let dir = std::env::temp_dir().join("lockpick_test_detect_yarn");
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();

        let content = r#"# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


react@^18.2.0:
  version "18.2.0"
  resolved "https://registry.yarnpkg.com/react/-/react-18.2.0.tgz"
  integrity sha512-fake
"#;
        fs::write(dir.join("yarn.lock"), content).unwrap();

        let graph = detect_and_parse(&dir).unwrap();
        assert_eq!(graph.lockfile_type, LockfileType::Yarn);

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_detect_empty_dir() {
        let dir = std::env::temp_dir().join("lockpick_test_detect_empty");
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();

        let result = detect_and_parse(&dir);
        assert!(result.is_err());

        let _ = fs::remove_dir_all(&dir);
    }
}
