pub mod npm;
pub mod pnpm;
pub mod yarn;

use std::collections::HashSet;
use std::path::Path;

use crate::DependencyGraph;
use crate::error::LockpickError;

/// Auto-detect and parse the lockfile in the given project directory.
/// Checks for pnpm-lock.yaml, package-lock.json, yarn.lock in that order.
pub fn detect_and_parse(project_dir: &Path) -> Result<DependencyGraph, LockpickError> {
    let candidates = [
        ("pnpm-lock.yaml", "pnpm" as &str),
        ("package-lock.json", "npm"),
        ("yarn.lock", "yarn"),
    ];

    for (filename, kind) in &candidates {
        let path = project_dir.join(filename);
        if path.exists() {
            let content = std::fs::read_to_string(&path)
                .map_err(LockpickError::Io)?;
            return match *kind {
                "pnpm" => pnpm::parse(&content),
                "npm" => npm::parse(&content),
                "yarn" => {
                    let dev_names = read_dev_dep_names(project_dir);
                    yarn::parse_with_dev_names(&content, &dev_names)
                }
                _ => unreachable!(),
            };
        }
    }

    Err(LockpickError::NoLockfile("No lockfile found (looked for pnpm-lock.yaml, package-lock.json, yarn.lock)".into()))
}

/// Read devDependencies names from package.json for yarn dev detection
fn read_dev_dep_names(project_dir: &Path) -> HashSet<String> {
    let pkg_path = project_dir.join("package.json");
    let content = match std::fs::read_to_string(&pkg_path) {
        Ok(c) => c,
        Err(_) => return HashSet::new(),
    };
    let json: serde_json::Value = match serde_json::from_str(&content) {
        Ok(v) => v,
        Err(_) => return HashSet::new(),
    };
    json.get("devDependencies")
        .and_then(|d| d.as_object())
        .map(|obj| obj.keys().cloned().collect())
        .unwrap_or_default()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::LockfileType;
    use std::fs;

    #[test]
    fn test_detect_pnpm() {
        let dir = tempfile::tempdir().unwrap();

        let content = r#"lockfileVersion: '9.0'
importers:
  .:
    dependencies:
      react:
        specifier: ^18.2.0
        version: 18.2.0
packages:
  react@18.2.0:
    resolution:
      integrity: sha512-fake
"#;
        fs::write(dir.path().join("pnpm-lock.yaml"), content).unwrap();

        let graph = detect_and_parse(dir.path()).unwrap();
        assert_eq!(graph.lockfile_type, LockfileType::Pnpm);
    }

    #[test]
    fn test_detect_npm() {
        let dir = tempfile::tempdir().unwrap();

        let content = r#"{
  "name": "test",
  "version": "1.0.0",
  "lockfileVersion": 3,
  "packages": {
    "": { "name": "test", "version": "1.0.0", "dependencies": { "react": "^18.2.0" } },
    "node_modules/react": { "version": "18.2.0", "resolved": "https://registry.npmjs.org/react/-/react-18.2.0.tgz", "integrity": "sha512-fake" }
  }
}"#;
        fs::write(dir.path().join("package-lock.json"), content).unwrap();

        let graph = detect_and_parse(dir.path()).unwrap();
        assert_eq!(graph.lockfile_type, LockfileType::Npm);
    }

    #[test]
    fn test_detect_yarn() {
        let dir = tempfile::tempdir().unwrap();

        let content = r#"# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


react@^18.2.0:
  version "18.2.0"
  resolved "https://registry.yarnpkg.com/react/-/react-18.2.0.tgz"
  integrity sha512-fake
"#;
        fs::write(dir.path().join("yarn.lock"), content).unwrap();

        let graph = detect_and_parse(dir.path()).unwrap();
        assert_eq!(graph.lockfile_type, LockfileType::Yarn);
    }

    #[test]
    fn test_detect_empty_dir() {
        let dir = tempfile::tempdir().unwrap();

        let result = detect_and_parse(dir.path());
        assert!(result.is_err());
    }
}
